### ISSUE TITLE
Clarity re format of "allProteinNamesWithEssentialityInformation.csv" 

### ISSUE THREAD

**Issue by LawsonSarah** [floklimm/hypergraph#1]
Hi,

Can you explain the format of the content in your file "allProteinNamesWithEssentialityInformation.csv" I'm looking to understand your paper "Hypergraphs for predicting essential genes using multiprotein complex data" in more detail and your mapping to essential genes.

Thanks!

Sarah

**Comment by floklimm** [comment]
Dear Sarah,

Thank you for your interest in our work. This file is indeed not well described. My apologies for that.

It contains a long list of all genes in our hypergraph for which there is essentiality data in the Online GEne Essentiality database (OGEE). Back then we used version two of this database. Meanwhile version 3 is out, so I would suggest that you use the most recent data, I am sure there is more data available now.

All the best,
Florian

**Comment by LawsonSarah** [comment]
Thanks, much appreciated!
