### ISSUE TITLE
Mapping gene to essentiality

### ISSUE THREAD

**Issue by LawsonSarah** [floklimm/hypergraph#2]
Hi,

In the file Homo-sapiens_consolidated there are multiple lines for one gene with differing definitions of  essentiality based on locus (e.g. for gene DHX16), how did you decide the mapping of your genes for the essentiality analysis in your paper?

Thanks!

Sarah

**Comment by floklimm** [comment]
Hello Sarah,

We marked a gene as essential if at least one of the loci are essential.

But more sophisticated approaches (e.g., majority rule) are certainly possible.

All the best,
Flo

**Comment by LawsonSarah** [comment]
Thanks for the quick response, much appreciate!

Sarah
